### ISSUE TITLE
Bug, sliding far too left cause anomaly

### ISSUE THREAD

**Issue by DangerBlack** [Ali-Azmoud/flutter_xlider#5]
When you place a custom FlutterSlider in a Column and you slide left too much, the widget trows an error.
```
I/flutter (19269): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19269): The following assertion was thrown building Container(bg: BoxDecoration(color: Color(0xffc5e1a5)),
I/flutter (19269): constraints: BoxConstraints(w=-0.7, h=5.0; NOT NORMALIZED), dirty):
I/flutter (19269): BoxConstraints has a negative minimum width.
I/flutter (19269): The offending constraints were:
I/flutter (19269):   BoxConstraints(w=-0.7, h=5.0; NOT NORMALIZED)
I/flutter (19269): 
I/flutter (19269): When the exception was thrown, this was the stack:
I/flutter (19269): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:504:9)
I/flutter (19269): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:532:19)
I/flutter (19269): #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:551:6)
I/flutter (19269): #3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:1969:27)
I/flutter (19269): #4      Container.build (package:flutter/src/widgets/container.dart:381:17)
I/flutter (19269): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (19269): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter (19269): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (19269): #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (19269): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (19269): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (19269): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (19269): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (19269): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (19269): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (19269): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (19269): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (19269): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (19269): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (19269): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (19269): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (19269): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (19269): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (19269): #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (19269): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (19269): #25     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
I/flutter (19269): #26     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter (19269): #27     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
I/flutter (19269): #28     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1728:58)
I/flutter (19269): #29     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
I/flutter (19269): #30     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1728:13)
I/flutter (19269): #31     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
I/flutter (19269): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (19269): #33     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (19269): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (19269): #35     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (19269): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (19269): #37     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (19269): #38     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:350:7)
I/flutter (19269): #39     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (19269): #40     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (19269): #41     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter (19269): #42     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (19269): #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
I/flutter (19269): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (19269): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (19269): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (19269): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (19269): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (19269): #52     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (19269): #53     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (19269): (elided 3 frames from package dart:async)
```

Possible fix:

```
Positioned _rightInactiveTrack() {
    double top, bottom, left, right, width, height;
    top = left = width = height = 0;
    right = bottom = null;

    if (widget.axis == Axis.horizontal) {
      bottom = 0;
      height = widget.trackBar.inactiveTrackBarHeight;
      print("here 6");
      width = _constraintMaxWidth -
          _rightHandlerXPosition -
          _handlersPadding -
          (widget.touchZone * 20 / 2);

      print("width "+width.toString());
      print("_rightHandlerXPosition "+_rightHandlerXPosition.toString());
      //BUGFIX HERE
      if(_rightHandlerXPosition<0){
         //FORCE ZERO
        _rightHandlerXPosition=0;
      }
      //FORCE 0 (not sure if it's necessary but still 
      if( _rightHandlerXPosition + (widget.touchZone * 20 / 2)>0) {
        left = _rightHandlerXPosition + (widget.touchZone * 20 / 2);
      }else{
        left =0;
      }
      print("left "+left.toString());
      if(left<0){
        left = 0;
      }
      print("left "+left.toString());
    } else {
      right = 0;
      width = widget.trackBar.inactiveTrackBarHeight;
      height = _constraintMaxHeight -
          _rightHandlerYPosition -
          _handlersPadding -
          (widget.touchZone * 20 / 2);
      top = _rightHandlerYPosition + (widget.touchZone * 20 / 2);
    }

//    if (widget.rangeSlider == true)
//      width = _constraintMaxWidth -
//          _rightHandlerXPosition -
//          _handlersPadding -
//          (widget.touchZone * 20 / 2);

    return Positioned(
      left: left,
      top: top,
      bottom: bottom,
      right: right,
      child: Center(
        child: Container(
          height: height,
          width: width,
          color: widget.trackBar.rightInactiveTrackBarColor,
        ),
      ),
    );
  }
```

**Comment by Ali-Azmoud** [comment]
Hi. Thanks for your report, I will fix that in the next version, I'm pretty sure I faced this exception before and fixed it in the latest version. Don't know how it still exists.

**Comment by Ali-Azmoud** [comment]
wow, what a big bug that was. I tested it today and noticed the bug, thank you again for your reporting. it's solved now

**Comment by Ali-Azmoud** [comment]
I close this issue, if you faced any related error, feel free to open this issue or make a new one
