### ISSUE TITLE
Exception when i let go of scrolling

### ISSUE THREAD

**Issue by febg11** [Ali-Azmoud/flutter_xlider#52]
When i let go of the scroller i get this exception 

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
_FlutterSliderState#30df9(tickers: tracking 4 tickers) was disposed with an active Ticker.

_FlutterSliderState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by _FlutterSliderState#30df9(lifecycle state: created, tickers: tracking 0 tickers))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:66:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:68:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:237:80)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:168:34)
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:245:21)
#5      _FlutterSliderState.initMethod (package:flutter_xlider/flutter_xlider.dart:342:46)
#6      _FlutterSliderState.initState (package:flutter_xlider/flutter_xlider.dart:253:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#33     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#65     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5219:32)
#66     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#74     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#76     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
#77     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#81     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
#82     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#92     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#96     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#97     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#98     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#99     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#100    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#101    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#105    _invoke (dart:ui/hooks.dart:259:10)
#106    _drawFrame (dart:ui/hooks.dart:217:3)
(elided 3 frames from package dart:async)

When the exception was thrown, this was the stack: 
#0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:185:13)
#1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:203:6)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435:12)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
...
```

**Comment by febg11** [comment]
IDo you need to add 
```
  @override
  void dispose() {
    _rightTooltipAnimationController.dispose();
    _leftTooltipAnimationController.dispose();
    _leftHandlerScaleAnimationController.dispose();
    _rightHandlerScaleAnimationController.dispose();
    super.dispose();
  }
````
to your class

**Comment by Ali-Azmoud** [comment]
Hi, thanks for your feedback and report, please open a PR for this.

**Comment by febg11** [comment]
Ok I will do this later today :)

Also  I have a problem with the onDraggingListener 

```
 onDragging: (handlerIndex, lowerValue, upperValue){

            double doubleVal = lowerValue;
            sliderValue = Duration(seconds: doubleVal.toInt());
            print(sliderValue);
            setState(() {});
        },
```
It doesnt seem to fire for many of the positions e.g. I scrolled from the start to end of the slider and the print output is this

```
flutter: 0:00:10.000000
flutter: 0:00:10.000000
flutter: 0:00:06.000000
flutter: 0:00:03.000000
flutter: 0:00:06.000000
flutter: 0:00:06.000000
flutter: 0:00:05.000000
flutter: 0:00:01.000000
flutter: 0:00:00.000000
flutter: 0:00:00.000000
flutter: 0:00:00.000000
        },
```

Do you know why it is missing so many positions? like 2,3,4 etc.

The slider has a range of 0-10 and i wasn't scrolling fast. 

It seems so fluid in your example 

![image](https://user-images.githubusercontent.com/50048162/80277844-c5aa5d80-86e9-11ea-94fc-b78cd85d616d.png)

**Comment by febg11** [comment]
I've sent you a pull request for the controller dispose. Do you want me to create another issue for my above problem?

**Comment by Ali-Azmoud** [comment]
if you set a big enough number for your `Max`, then a tiny movement will miss many positions I guess. It's not a bug.

**Comment by Ali-Azmoud** [comment]
I will test this and let you know.

**Comment by Ali-Azmoud** [comment]
This is my result

![](http://flutterdev.site/public/images/slider.gif)

```
I/flutter ( 4338): 26.0
I/flutter ( 4338): 25.0
I/flutter ( 4338): 24.0
I/flutter ( 4338): 23.0
I/flutter ( 4338): 22.0
I/flutter ( 4338): 21.0
I/flutter ( 4338): 21.0
I/flutter ( 4338): 20.0
I/flutter ( 4338): 19.0
I/flutter ( 4338): 19.0
I/flutter ( 4338): 17.0
I/flutter ( 4338): 17.0
I/flutter ( 4338): 16.0
I/flutter ( 4338): 15.0
I/flutter ( 4338): 14.0
I/flutter ( 4338): 11.0
I/flutter ( 4338): 9.0
I/flutter ( 4338): 8.0
I/flutter ( 4338): 6.0
I/flutter ( 4338): 4.0
I/flutter ( 4338): 2.0
I/flutter ( 4338): 0.0
I/chatty  ( 4338): uid=10086(com.fatap.flutterappslider) Thread-2 identical 11 lines
I/flutter ( 4338): 0.0
```

**Comment by febg11** [comment]
Strange. I only have 

```
 onDragging: (handlerIndex, lowerValue, upperValue){

            double doubleVal = lowerValue;
            sliderValue = Duration(seconds: doubleVal.toInt());
            print(sliderValue);
            setState(() {});
        },
```

I tried adding the tooltip back on to the slider and that works fine for incrementing the text counter. 
I would prefer to use the tooltip you have created rather than my static Text() widget but I am unable to get it to be on the left hand side on a vertical slider.

e.g. 
![Screenshot 2020-04-26 at 19 55 33](https://user-images.githubusercontent.com/50048162/80316848-258f2a00-87f8-11ea-8f90-4566c2025a68.png)

Would it be hard to have this as a feature in the library? I am not great with flutter and I'm not sure how hard this is to do.

**Comment by Ali-Azmoud** [comment]
In order to display your own tooltip, you can use `tooltip` property, `FlutterSliderTooltip`, `TextStyle`, `BoxStyle` or just use `custom` and create your own tooltip widget from scratch.

**Comment by febg11** [comment]
ok thank you

**Comment by Ali-Azmoud** [comment]
it's done. I am testing it. there are a bunch of options in this package which may take effect

**Comment by febg11** [comment]
Nice! When do you think they will be available on pub.dev for me to use?

**Comment by Ali-Azmoud** [comment]
Hi, missing-positions is fixed in the latest version. check it out.

**Comment by febg11** [comment]
It works perfectly. Thanks a lot for adding this feature :)
